# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.SlugField()),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('downloads', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=10)),
                ('ispublic', models.BooleanField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='')),
                ('filetype', models.PositiveIntegerField(choices=[(1, 'map'), (2, 'localization'), (3, 'music'), (4, 'other')], default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMapType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_short', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upvote', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='maptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.ProjectMapType'),
        ),
    ]
