# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_squashed_0016_auto_20160501_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='date_registered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
