# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectVotes',
            new_name='ProjectVote',
        ),
    ]
