# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 16:42
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20160207_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='thumbnails/'),
        ),
    ]
