# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_yuki'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yuki',
            new_name='RegUser',
        ),
    ]
