# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20160426_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
