# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20160427_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messsage',
            new_name='message',
        ),
    ]
