# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 14:16
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20160427_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='profile_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='profile_images/'),
        ),
    ]
