# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 17:26
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_reguser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='profile_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
