# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 14:45
from __future__ import unicode_literals

from django.db import migrations

# Uh ignore this...

class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_auto_20160427_1926'),
    ]

    operations = [
    ]
