# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_auto_20160501_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='about',
            field=models.TextField(blank=True, default="I'm a metalface", null=True),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='activation_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
