# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    replaces = [('info', '0001_initial'), ('info', '0002_auto_20160427_2017')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('text', django_markdown.models.MarkdownField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
