# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
