# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_stream'),
        ('info', '0002_auto_20160206_1608'),
    ]

    operations = [
    ]
